--------------------------------------------------------
--  파일이 생성됨 - 금요일-1월-03-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOARD" 
   (	"NUM" NUMBER, 
	"WRITER" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"SUBJECT" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(10 BYTE), 
	"REG_DATE" DATE, 
	"REF" NUMBER, 
	"RE_STEP" NUMBER, 
	"RE_LEVEL" NUMBER, 
	"READCOUNT" NUMBER, 
	"CONTENT" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.BOARD
SET DEFINE OFF;
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (2,'1','1@gmail.com','1','1',to_date('25/01/01','RR/MM/DD'),1,1,1,1,'1');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (3,'2','2@gmail.com','2','2',to_date('25/01/01','RR/MM/DD'),2,1,1,8,'2');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (4,'3','3@gmail.com','3','3',to_date('25/01/01','RR/MM/DD'),3,1,1,5,'3');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (22,'22','2@gmail.com','[답변]22','22',to_date('25/01/01','RR/MM/DD'),2,2,4,4,'22');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (23,'222','2@gmail.com','[답변]222','222',to_date('25/01/01','RR/MM/DD'),2,2,2,13,'222');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (24,'2222','2@gmail.com','[답변]2222-modify','2222',to_date('25/01/01','RR/MM/DD'),2,3,3,7,'2222-modify');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (41,'6','0@gmail.com','6','6',to_date('25/01/03','RR/MM/DD'),6,1,1,0,'6');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (5,'4','0@gmail.com','4','4',to_date('25/01/03','RR/MM/DD'),4,1,1,0,'4');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (21,'5','0@gmail.com','5','5',to_date('25/01/03','RR/MM/DD'),5,1,1,0,'5');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (42,'7','0@gmail.com','7','7',to_date('25/01/03','RR/MM/DD'),7,1,1,0,'7');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (43,'8','0@gmail.com','8','8',to_date('25/01/03','RR/MM/DD'),8,1,1,0,'8');
Insert into SYSTEM.BOARD (NUM,WRITER,EMAIL,SUBJECT,PASSWORD,REG_DATE,REF,RE_STEP,RE_LEVEL,READCOUNT,CONTENT) values (44,'9','0@gmail.com','9','9',to_date('25/01/03','RR/MM/DD'),9,1,1,1,'9');
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."BOARD_PK" ON "SYSTEM"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("REF" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("RE_STEP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("RE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("READCOUNT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("NUM")
  USING INDEX "SYSTEM"."BOARD_PK"  ENABLE;
